services:
  todo-api:
    image: todo-api
    pull_policy: never
    build:
      context: .
      dockerfile: TodoApi.Api/Dockerfile
      target: final
    ports:
      - "8080:8080"
  
  postgres:
    image: postgres:18-trixie
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
